config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'splash#index'
 resources :splash, only: [:index]
 resources :categories do
  resources :exchanges
end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:

    user ||= User.new

    return unless user.present?

    can :read, :all

    if user.is? :admin
      can :manage, :all
    else
      can :read, :all
    end

    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :slots
  has_many :exchanges, through: :slots

  validates_presence_of :user
  validates :name, presence: true, length: { maximum: 30 }
  validates :icon, presence: true

  def total_amount
    total = 0
    exchanges.each do |exchange|
      total += exchange.amount
    end
    total
  end
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :slots, dependent: :destroy
  has_many :categories, through: :slots

  validates_presence_of :name, :amount, :author
end

app/models/slot.rb
class Slot < ApplicationRecord
  belongs_to :category
  belongs_to :exchange
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ROLES = %i[admin default].freeze

  def is?(requested_role)
    role == requested_role.to_s
  end

  has_many :categories
  has_many :exchanges, foreign_key: 'author_id'

  validates :name, presence: true, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :avatar, { roles: [] }])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @categories = Category.where(user: current_user)
  end

  def show
    @expenses = @category.exchanges.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def edit; end

  def create
    @category = Category.new(category_params)
    @category.user = current_user

    if @category.save
      flash[:success] = 'Category successfully created'
      redirect_to categories_path
    else
      flash[:error] = 'Something went wrong'
      render 'new'
    end
  end

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:success] = 'category was successfully deleted.'
      redirect_to categories_path
    else
      flash[:error] = 'Something went wrong'
      render :show
    end
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :set_exchanges, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    @category = Category.find(params[:category_id])
    @exchanges = @category.exchanges.order(created_at: :desc)

    redirect_to new_user_session_path, notice: 'can not access this resource' if @category.user != current_user
  end

  def new
    @category = Category.find(params[:category_id])
    @exchange = Exchange.new
  end

  def create
    @exchange = Exchange.new(exchange_params)
    @exchange.author = current_user
    @category = Category.find(params[:category_id])
    @category.exchanges << @exchange

    respond_to do |format|
      if @exchange.save
        format.html do
          redirect_to category_exchanges_path(@category), notice: 'Transaction was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to category_url(@category), notice: 'Exchange was successfully destroyed.' }
    end
  end

  private

  def set_exchanges
    @exchanges = Exchange.find(params[:id])
  end

  def exchange_params
    params.require(:exchange).permit(:name, :amount)
  end
end

app/controllers/slot_controller.rb
class SlotController < ApplicationController
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  def index
    redirect_to categories_path if user_signed_in?
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/exchange_helper.rb
module ExchangeHelper
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/slot_helper.rb
module SlotHelper
end

app/helpers/splash_helper.rb
module SplashHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>"  class="category">
  <div class="desc">
  <div class="list_image"><img src="<%= category.icon%>" class="w-24"></div>
  <div><%= category.name%></div>
  <div>$<%= category.total_amount %></div>
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with model: category, url: categories_path, :html => {:class => 'form', :id => 'form' }  do |f| %>
       <div class="field">
        <%= f.text_field :name, autofocus: true, autocomplete: "text", placeholder: "Enter category name" %>
        <% category.errors.full_messages_for(:name).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
       <div class="field">
       <p class="category-title"> Choose an icon </p>
       <div class="icons">
        <%= f.radio_button :icon, "fast-food-outline" %>
        <%= f.label :icon, :value => "fast-food-outline" do%>
            <ion-icon name="fast-food-outline" class="transaction-img food" value="food"></ion-icon>
        <% end %>
        <%= f.radio_button :icon, "headset" %>
        <%= f.label :icon, :value => "headset" do%>
          <ion-icon name="headset" class="transaction-img headset" value="headset"></ion-icon>
        <% end %>
        <%= f.radio_button :icon, "bulb" %>
        <%= f.label :icon, :value => "bulb" do%>
          <ion-icon name="bulb" class="transaction-img bulb" value="bulb"></ion-icon>
        <% end %>
        <%= f.radio_button :icon, "football" %>
        <%= f.label :icon, :value => "football" do%>
          <ion-icon name="football" class="transaction-img football" value="football"></ion-icon>
        <% end %>
        <%= f.radio_button :icon, "barbell" %>
        <%= f.label :icon, :value => "barbell" do%>
          <ion-icon name="barbell" class="transaction-img barbell" value="barbell"></ion-icon>
        <% end %>
        <!-- car -->
        <%= f.radio_button :icon, "car" %>
        <%= f.label :icon, :value => "car" do%>
          <ion-icon name="car" class="transaction-img car" value="car"></ion-icon>
        <% end %>
        <!-- call -->
        <%= f.radio_button :icon, "call" %>
         <%= f.label :icon, :value => "call" do%>
          <ion-icon name="call" class="transaction-img call" value="call"></ion-icon>
        <% end %>
        <!-- bus -->
        <%= f.radio_button :icon, "book" %>
         <%= f.label :icon, :value => "book" do%>
          <ion-icon name="book" class="transaction-img book" value="Education"></ion-icon>
        <% end %>
        <!-- game-controller -->
        <%= f.radio_button :icon, "game-controller" %>
        <%= f.label :icon, :value => "game-controller" do%>
          <ion-icon name="game-controller" class="transaction-img game-controller" value="Games"></ion-icon>
        <% end %>
        <!-- home -->
        <%= f.radio_button :icon, "home" %>
        <%= f.label :icon, :value => "home" do%>
          <ion-icon name="home" class="transaction-img home" value="home"></ion-icon>
        <% end %>
        <!-- shirt -->
        <%= f.radio_button :icon, "shirt" %>
        <%= f.label :icon, :value => "shirt" do%>
          <ion-icon name="shirt" class="transaction-img shirt" value="shirt"></ion-icon>
        <% end %>
        <!-- bandage -->
        <%= f.radio_button :icon, "bandage" %>
        <%= f.label :icon, :value => "bandage" do%>
          <ion-icon name="bandage" class="transaction-img bandage" value="bandage"></ion-icon>
        <% end %>
      </div>
        <% category.errors.full_messages_for(:icon).each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>

       <div id="actions">
      <%= f.submit "Add", id: 'category-btn'%>
    </div>
<% end %>

app/views/categories/edit.html.erb
 <div class="edit_category">
    <h2> Edit Category</h2>
    <%= render "form", category: @category %>
    <div>
    <%= link_to "About Category", @category %> |
    <%= link_to "Back To Categories", category_path %>
  </div>
 </div>

app/views/categories/index.html.erb
<section class='categories_controllers'>
  <header class="category-header">
    <div class="user-info">
    
      <div class="user-details">
        <p class="welcome">Welcome!</p>
        <h2 class="user-name"><%= current_user.name %></h2>
      </div>
    </div>
    <li class="logout">
      <%= button_to "Logout", destroy_user_session_path(current_user), method: :delete %>
    </li>
  </header>
  <div class="category-section">
     <h2 class="all-transaction">All Transactions</h2>
     <div class="add-category-wrapper">
        <div class="add-new-category">
          <%= button_to "+", new_category_path, method: :get, class: 'category-btnn' %>
        </div>
        <p>Create new category</p>
     </div>
     <% if @categories.exists? %>
      <ul class="category-lists-wrapper">
          <% @categories.each do |category| %>
           <%= link_to category_path(category.id), method: :get do %>
          <li>

            <div class='desc'>
            <ion-icon name="<%= category.icon %>" class="list-image transaction-img <%= category.icon %>"></ion-icon>
              <span class="desc-text">
                <p><%= category.name %></p>
                <small><%= category.created_at.to_date.strftime("%d %b, %Y") %></small>
              </span>
            </div>
              <p class='strong'>- $<%= category.exchanges.sum(:amount) || '0.00'%>

              </p>
          </li>
          <% end %>
          <% end %>
      </ul>
   <% else %>
          <p class="nil-category">No Category Added yet</p>
      <% end %>
  <div>
</div>
</section>

app/views/categories/new.html.erb
<section class="user-input-container">
  <header class="input-container">
    <nav>
      <ul class='links'>
        <li>
        <%= link_to categories_path do %>
          <i class="fa fa-arrow-left"></i>
          <% end %>
        </li>
        <li>
          ADD CATERGORY
        </li>
        <li class='login'>
          <input type="submit" value='Add' form='form' class='submit'>
        </li>
      </ul>
    </nav>
  </header>
    <%= render "form", category: @category %>
  
 
</section>

app/views/categories/show.html.erb
<section class="categories_controllers">
  <header class="input-container">
    <nav>
      <ul class='links'>
        <li>
        <%= link_to categories_path do %>
          <i class="fa fa-arrow-left"></i>
          <% end %>
        </li>
        <li>
          DETAILS
        </li>
        <li>
          <i class="fa fa-bars"></i>
        </li>
      </ul>
    </nav>
  </header>
  <section class="category-section details ">
    <div class='payment'>
      <p>TOTAL EXPENSES</p>
      <h2>$<%= @category.exchanges.sum(:amount) || '0.00' %></h2>
      <div class='desc'>
        <ion-icon id="list-img" name="<%= @category.icon %>"  class="transaction-img <%= @category.icon %>"></ion-icon>
        <span>
          <h3><%= @category.name %></h3>
        </span>
      </div>
    </div>
      <% if @transactions.present?%>
        <div class="transaction-container">
    <hr>
    <% @transactions.each do |transaction| %>
    <div class='transaction'>
      <span>
        <h3><%= transaction.name %></h3>
        <small><%= transaction.created_at.to_date.strftime("%d %b, %Y") %></small>
      </span>
      <span>
         <%= button_to "Remove", category_exchange_path(@category,transaction), method: :delete, class: 'delete-transaction' %>
      </span>
    </div>
    <hr>

   <% end %>
    <%= button_to "Delete Category", category_path, method: :delete, class: 'delete-categories' %>
</div>
  <% else %>
  <p></p>
  <% end %>

  </section>
  <div class='category-footer'>
    <%= button_to "+", new_category_exchange_path(@category), method: :get, class: 'category-btn' %>
    <p>Add New Transaction
  </div>
</section>

app/views/exchanges/_exchange.html.erb
<div class="category">
  <div class="expense-container">
  <div><%= exchange.name %></div>
  <div class="exchange_amount">Amount Spent: $<%= exchange.amount%></div>
   <p class="expense-date"><%= exchange.created_at.strftime('%d %B %Y') %></p>
  </div>
</div>

app/views/exchanges/_form.html.erb
<div class="forms_section">
 <%= form_with model: @exchange, url: category_exchanges_path, :html => {:class => 'form', :id => 'form' }  do |form| %>
    <% if @exchange.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(exchange.errors.count, "error") %> prohibited this exchange from being saved:</h2>

        <ul>
          <% exchange.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name, class: "label" %> <br> 
      <%= form.text_field :name, placeholder: "Enter the transaction's name" %>
    </div>

    <div class="field">
      <%= form.label :amount, class: "label" %> <br>
      <%= form.number_field :amount, min: 0, placeholder: "Enter the transaction's amount" %>
    </div>

    <div class="actions">
      <%= form.submit 'Add New Transaction', class: "category-btn" %>
    </div>
  <% end %>
</div>

app/views/exchanges/index.html.erb
<section class="user-input-container">
  <header class="input-container">
    <nav>
      <ul class='links'>
        <li>
        <%= link_to categories_path do %>
          <i class="fa fa-arrow-left"></i>
          <% end %>
        </li>
        <li>
          ADD TRANSACTION
        </li>
        <li class='login'>
          <input type="submit" value='Add' form='form' class='submit'>
        </li>
      </ul>
    </nav>
  </header>
  
   <%= render partial: "form", locals: { exchange: @exchange, categories: @categories } %>
</section>

app/views/exchanges/new.html.erb
<section class="user-input-container">
  <header class="input-container">
    <div class="links">
      <%= link_to category_exchanges_path , method: :get, class: "back_btn text_white" do %>
        <i class="fa fa-arrow-left"></i>
      <% end %>
    </div>
    <h2 class="text_white">Create New Transaction</h2>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "submit" %>
  </header>
  <div class="center">
    <%= render "form", exchange: @exchange %>
  </div>
</section>

app/views/exchanges/show.html.erb
<%= render exchange %>

<section class>
<div class="desc">
  <%= link_to "< Back", exchanges_path %>
  <%= link_to "Edit", edit_exchange_path(@exchange) %>
  <%= link_to "Delete", @exchange, method: :delete %>
</div>
</section>